apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
spec:
  rules:
    - host: { { .Values.ingress.host } }
      http:
        paths:
          - path: { { .Values.ingress.path } }
            pathType: Prefix
            backend:
              service:
                name: app1
                port:
                  number: { { .Values.service.port } }
