apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: { { .Values.service.port } }
      targetPort: 8080
  type: { { .Values.service.type } }
